# Generated by Django 3.0.5 on 2021-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='product_id', primary_key=True, serialize=False)),
                ('brand', models.CharField(db_column='brand', default=None, max_length=300)),
                ('product_name', models.CharField(db_column='product_name', max_length=500)),
                ('old_price', models.DecimalField(db_column='old_price', decimal_places=2, max_digits=6)),
                ('new_price', models.DecimalField(db_column='new_price', decimal_places=2, max_digits=6)),
                ('image', models.CharField(db_column='IMAGE', max_length=5000)),
                ('link', models.CharField(db_column='link', max_length=500)),
                ('discount', models.DecimalField(db_column='discount', decimal_places=2, default=None, max_digits=5)),
                ('sizes', models.CharField(db_column='sizes', default=None, max_length=250)),
                ('colors', models.CharField(db_column='colors', default=None, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
